kind: pipeline
type: docker
name: front-haiji-api

steps:
- name: tag
  image: registry.cn-hangzhou.aliyuncs.com/epet/alpine:latest
  pull: if-not-exists
  commands:
    - echo -n 'test_'`date +%m-%d_%H-%M-%S`,latest > .tags

- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    username: 
      from_secret: epet_docker_username
    password: 
      from_secret: epet_docker_password
    repo: registry-vpc.cn-hangzhou.aliyuncs.com/gott/${DRONE_REPO_NAME}
    registry: registry-vpc.cn-hangzhou.aliyuncs.com

- name: synchronization
  image: appleboy/drone-scp
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_dev_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    secure: true
    target: /www/shell
    source: ./${DRONE_REPO_NAME}.yaml

- name: deploy
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_dev_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    script: |
              if kubectl apply -f /www/shell/${DRONE_REPO_NAME}.yaml --record=true | grep -q unchanged; then
                echo '=> Patching deployment to force image update.'
                kubectl patch -f /www/shell/${DRONE_REPO_NAME}.yaml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
              else
                 echo '=> Deployment apply has changed the object, no need to force image update.'
              fi

              timeout 120 kubectl rollout status deployment/${DRONE_REPO_NAME}-k8s -n gott


- name: dingtalk
  image: guoxudongdocker/drone-dingtalk
  pull: if-not-exists
  settings:
    token: 52cef6699ae2e9ffd6962446ae27716
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
    tips_title: dev
  when:
    status: [failure, success]

node:
  runner: epet
  ecs: jenkins

trigger:
  branch:
    - dev
  event:
    - push


