apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    alicloud-pvname: share-workflow-pv
  name: share-workflow-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: share-workflow-pvc
    namespace: gott
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /share/share-workflow
      server: 007ddc75-w9jq.cn-hangzhou.extreme.nas.aliyuncs.com
      vers: '3'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
