apiVersion: v1
kind: Service
metadata:
  name: workflow-svc
  namespace: gott
  labels:
    istio: gott-share-workflow-svc
spec:
  selector:
    istio: gott-share-workflow
  ports:
  - name: http-workflow
    port: 9002
    targetPort: 9002
    protocol: TCP