- hosts:        kubernetes_dev
  remote_user:  root

  tasks:
    - name:     create directory
      file:     'dest=/www/shell/  state=directory'

    - name:     delete kubernetes yaml file
      file:     'dest=/www/shell/kubernetes-{{ service_name }}.yml state=absent'


    - name:     Write the kubernetes yaml file
      template: 'src=templates/kubernetes.conf.j2 dest=/www/shell/kubernetes-{{ service_name }}.yml mode=0755'

    - name:     start service
      shell: |    
                  if kubectl apply -f /www/shell/kubernetes-{{ service_name }}.yml --record=true | grep -q unchanged; then
                    echo '=> Patching deployment to force image update.'
                    kubectl patch -f /www/shell/kubernetes-{{ service_name }}.yml -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-last-updated\":\"$(date +'%s')\"}}}}}"
                  else
                    echo '=> Deployment apply has changed the object, no need to force image update.'
                  fi    

    - name:     get desired num
      shell:    "kubectl get deployment  -n {{ namespace }} | grep {{ service_name }} | awk '{print $3}'"
      register: desired
    - debug:    msg="{{ desired.stdout }}"

    - name:     get current num
      shell:    "kubectl get deployment  -n {{ namespace }} | grep {{ service_name }} | awk '{print $4}'"
      register: current
      delay:    5
      retries:  38
      until:    current.stdout == desired.stdout
