apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gott-share-workflow
    istio: gott-share-workflow
  name: gott-share-workflow-k8s
  namespace: gott
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gott-share-workflow
      istio: gott-share-workflow
  strategy:
    rollingUpdate:
      maxSurge: 26%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gott-share-workflow
        istio: gott-share-workflow
        security.istio.io/tlsMode: istio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cn-hangzhou.172.16.5.166
                - cn-hangzhou.172.16.5.167
            weight: 100
      containers:
      - env:
        - name: ENVIRONMENT
          value: product
        - name: IS_K8S
          value: "1"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVICE_ADDR
          value: workflow.internal.service.com:80
        - name: CONSUL_PORT
          value: "8500"
        - name: SERVER_PORT
          value: "9002"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.cn-hangzhou.aliyuncs.com/gott/gott-share-workflow:20200521135441
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - php
              - bin/server
              - stop
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /app-health/gott-share-workflow/livez
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: gott-share-workflow
        ports:
        - containerPort: 9002
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /app-health/gott-share-workflow/readyz
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 6
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 5m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /wwwlogs
          name: gott-share-workflow-volume
      - args:
        - proxy
        - sidecar
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - gott-share-workflow.$(POD_NAMESPACE)
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istiod.istio-system.svc:15012
        - --zipkinAddress
        - zipkin.istio-system:9411
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --connectTimeout
        - 10s
        - --proxyAdminPort
        - "15000"
        - --concurrency
        - "2"
        - --controlPlaneAuthPolicy
        - NONE
        - --dnsRefreshRate
        - 300s
        - --statusPort
        - "15020"
        - --trust-domain=cluster.local
        - --controlPlaneBootstrap=false
        env:
        - name: JWT_POLICY
          value: first-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istio-pilot.istio-system.svc:15012
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":9002,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: |-
            [
                gott-share-workflow
            ]
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ISTIO_META_CONFIG_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_META_WORKLOAD_NAME
          value: gott-share-workflow-k8s
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/gott/deployments/gott-share-workflow-k8s
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{"/app-health/gott-share-workflow/livez":{"httpGet":{"path":"/v1/receive/check","port":9002,"scheme":"HTTP"},"timeoutSeconds":5},"/app-health/gott-share-workflow/readyz":{"httpGet":{"path":"/v1/receive/check","port":9002,"scheme":"HTTP"},"timeoutSeconds":6}}'
        image: docker.io/istio/proxyv2:1.5.2
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15020
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/pod
          name: podinfo
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: private-image-secret
      - name: rdc-cluster-image-pull-sercret-registry.cn-hangzhou.aliyuncs.com
      initContainers:
      - command:
        - istio-iptables
        - -p
        - "15001"
        - -z
        - "15006"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - '*'
        - -d
        - 15090,15020
        image: docker.io/istio/proxyv2:1.5.2
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: gott-share-workflow-volume
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - configMap:
          defaultMode: 420
          name: istio-ca-root-cert
        name: istiod-ca-cert