kind: pipeline
type: docker
name: test-v2

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    username: 
      from_secret: epet_docker_username
    password: 
      from_secret: epet_docker_password
    repo: registry-vpc.cn-hangzhou.aliyuncs.com/gott/${DRONE_REPO_NAME}
    registry: registry-vpc.cn-hangzhou.aliyuncs.com
    tag: ${DRONE_COMMIT_BRANCH:8}-${DRONE_COMMIT_SHA:0:8}
    dockerfile: ./build/Dockerfile-${DRONE_COMMIT_BRANCH:8}

- name: synchronization
  image: appleboy/drone-scp
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_${DRONE_COMMIT_BRANCH:8}_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    secure: true
    target: /www/shell 
    source: ./build/${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH:8}.yaml

- name: deploy
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_${DRONE_COMMIT_BRANCH:8}_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    script: |
              if kubectl get pod -n gott | grep -v "grep" | grep ${DRONE_REPO_NAME}; then
                sed -i 's/imagetag/${DRONE_COMMIT_BRANCH:8}-${DRONE_COMMIT_SHA:0:8}/g' /www/shell/build/${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH:8}.yaml
                kubectl set image deployment/${DRONE_REPO_NAME} ${DRONE_REPO_NAME}=registry-vpc.cn-hangzhou.aliyuncs.com/gott/${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH:8}-${DRONE_COMMIT_SHA:0:8} -n gott --record=true
              else
                sed -i 's/imagetag/${DRONE_COMMIT_BRANCH:8}-${DRONE_COMMIT_SHA:0:8}/g' /www/shell/build/${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH:8}.yaml
                kubectl apply -f /www/shell/build/${DRONE_REPO_NAME}-${DRONE_COMMIT_BRANCH:8}.yaml --record=true
              fi

              timeout 300 kubectl rollout status deployment/${DRONE_REPO_NAME} -n gott


- name: dingtalk
  image: guoxudongdocker/drone-dingtalk
  pull: if-not-exists
  settings:
    token: f6aa23a3e3d635704a1111111111111111111
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
    tips_title: dev
  when:
    status: [failure, success]

node:
  runner: epet
  ecs: jenkins

trigger:
  branch:
    - release/*
  event:
    - push


