kind: pipeline
type: docker
name: front-haiji-api

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    username: 
      from_secret: epet_docker_username
    password: 
      from_secret: epet_docker_password
    repo: registry-vpc.cn-hangzhou.aliyuncs.com/gott/${DRONE_REPO_NAME}
    registry: registry-vpc.cn-hangzhou.aliyuncs.com
    tag: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}

- name: synchronization
  image: appleboy/drone-scp
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_dev_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    secure: true
    target: /www/shell
    source: ./${DRONE_REPO_NAME}.yaml

- name: deploy
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host: 
      from_secret: k8s_dev_host
    port: 
      from_secret: k8s_ssh_port
    user: 
      from_secret: k8s_ssh_username
    key:
      from_secret: k8s_ssh_222key
    script: |
              if kubectl get pod -n gott | grep -v "grep" | grep ${DRONE_REPO_NAME}; then
                sed -i 's/imagetag/${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}/g' /www/shell/${DRONE_REPO_NAME}.yaml
                kubectl set image deployment/${DRONE_REPO_NAME} ${DRONE_REPO_NAME}=registry-vpc.cn-hangzhou.aliyuncs.com/gott/${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8} -n gott --record=true
              else
                sed -i 's/imagetag/${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}/g' /www/shell/${DRONE_REPO_NAME}.yaml
                kubectl apply -f /www/shell/${DRONE_REPO_NAME}.yaml --record=true
              fi

              timeout 120 kubectl rollout status deployment/${DRONE_REPO_NAME} -n gott


- name: dingtalk
  image: guoxudongdocker/drone-dingtalk
  pull: if-not-exists
  settings:
    token: f6aa23a3e3d635704a91ed9a64fe42148ad140e7e0d6bc282d8995641f0b1a1d
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
    tips_title: dev
  when:
    status: [failure, success]

node:
  runner: epet
  ecs: jenkins

trigger:
  branch:
    - dev
  event:
    - push


