apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-parent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-parent
    spec:
      containers:
      - args:
        - java
        - -XX:+UseParallelGC
        - -XX:+UseParallelOldGC
        - -Xms512M
        - -Xmx512M
        - -Xmn300M
        - -XX:SurvivorRatio=8
        - -XX:MetaspaceSize=600M
        - -XX:+PrintGCDetails
        - -XX:+PrintGCDateStamps
        - -XX:+PrintHeapAtGC
        - -Xloggc:/log/gc.log
        - -XX:+HeapDumpOnOutOfMemoryError
        - -XX:HeapDumpPath=/log/dump.bin
        - -Djava.security.egd=file:/dev/./urandom
        - -Dfile.encoding=UTF8
        - -Duser.timezone=GMT+08
        - -jar
        - microservices-user.jar
        env:
        - name: ENVIRONMENT
          value: dev
        - name: SERVICE_ADDR
          value: user.dev.internal.service.com
        - name: IS_K8S
          value: "1"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: user-parent:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sleep 60
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/k8s-liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: user-parent
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/k8s-readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 5m
            memory: 500Mi
        volumeMounts:
        - mountPath: /wwwlogs
          name: user-parent-volume
      imagePullSecrets:
      - name: private-image-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 90
      volumes:
      - emptyDir: {}
        name: user-parent-volume